/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package passing.build;

public class App {
    public String getGreeting() {
        return "This is a testing project which should build correctly.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
